"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var jsx_runtime_1 = require("react/jsx-runtime");
var fa_1 = require("react-icons/fa");
var TeamMemberCard = function (_a) {
    var image = _a.image, name = _a.name, role = _a.role;
    return ((0, jsx_runtime_1.jsxs)("div", { className: "bg-white p-6 rounded-lg shadow-lg text-center", children: [(0, jsx_runtime_1.jsx)("div", { className: "w-full h-[400px] mb-4 overflow-hidden border-b-4 border-yellow-500", children: (0, jsx_runtime_1.jsx)("img", { src: image, alt: name, className: "w-full h-full object-cover" }) }), (0, jsx_runtime_1.jsxs)("div", { className: "bg-white p-4 rounded-lg mx-4 shadow-md mt-4", children: [(0, jsx_runtime_1.jsx)("h3", { className: "text-xl font-semibold", children: name }), (0, jsx_runtime_1.jsx)("p", { className: "text-gray-600", children: role }), (0, jsx_runtime_1.jsxs)("div", { className: "flex justify-center space-x-4 mt-4", children: [(0, jsx_runtime_1.jsx)("a", { href: "#", className: "w-10 h-10 rounded-full bg-[#FAF5EF] flex items-center justify-center text-blue-500 hover:bg-[#F7A235]  transition-colors duration-300", children: (0, jsx_runtime_1.jsx)(fa_1.FaFacebookF, {}) }), (0, jsx_runtime_1.jsx)("a", { href: "#", className: "w-10 h-10 rounded-full bg-[#FAF5EF] flex items-center justify-center text-blue-400 hover:bg-[#F7A235] transition-colors duration-300", children: (0, jsx_runtime_1.jsx)(fa_1.FaTwitter, {}) }), (0, jsx_runtime_1.jsx)("a", { href: "#", className: "w-10 h-10 rounded-full bg-[#FAF5EF] flex items-center justify-center text-blue-700 hover:bg-[#F7A235] transition-colors duration-300", children: (0, jsx_runtime_1.jsx)(fa_1.FaLinkedinIn, {}) })] })] })] }));
};
var MeetTheTeam = function () {
    return ((0, jsx_runtime_1.jsx)("div", { className: "max-w-7xl mx-auto py-12", children: (0, jsx_runtime_1.jsxs)("div", { className: "grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-8", children: [(0, jsx_runtime_1.jsx)(TeamMemberCard, { image: "images/Robertsmith.jpg", name: "Robert Smith", role: "Director" }), (0, jsx_runtime_1.jsx)(TeamMemberCard, { image: "images/johnAlbert.jpg", name: "John Albert", role: "Engineer" }), (0, jsx_runtime_1.jsx)(TeamMemberCard, { image: "images/MikeHardson.jpg", name: "Mike Hardson", role: "Installer" }), (0, jsx_runtime_1.jsx)(TeamMemberCard, { image: "images/kevinjones.jpg", name: "Kevin Jones", role: "Director" }), (0, jsx_runtime_1.jsx)(TeamMemberCard, { image: "images/janecooper.jpg", name: "Jane Cooper", role: "Engineer" }), (0, jsx_runtime_1.jsx)(TeamMemberCard, { image: "images/arthurchen.jpg", name: "Arthur Chen", role: "Installer" })] }) }));
};
exports.default = MeetTheTeam;
